GameZone/Controllers/GamesController.cs
using GameZone.Models;
using GameZone.Models.viewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GameZone.Controllers
{
    public class GamesController : Controller
    {
        private readonly AppDbcontext _context;

        public GamesController(AppDbcontext context)
        {
            _context = context;
        }
   
        
    }
}

GameZone/Controllers/HomeController.cs
using GameZone.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GameZone.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

      

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GameZone/Views/Games/Create.cshtml
@model CreateGameformviewModel
@{
    ViewData["Title"] = "Add Game";
}
 <h5>
    <i class="bi bi-plus-circle-ditted"></i>
     Add Game
     </h5>

<form asp-controller="Games" asp-action="Save">
<div class="row">
    <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Name" class="form-label mt-4"></label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Enter Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="form-label mt-4"></label>
                <input type="text" class="form-control" asp-for="Description" placeholder="Enter Name">
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-light text-black mt-4">Save</button>
    </div>

</div>
</form>

GameZone/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<sidebar class="align-content-lg-center">
   <ul>
       <li>
           jdlkgfsldkj
       </li><li>
           jdlkgfsldkj
        </li>
        <li>
            jdlkgfsldkj
        </li>
        <li>
            jdlkgfsldkj
        </li>
   </ul>
</sidebar>

GameZone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GameZone | @ViewData["Title"] </title>
    <link rel ="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameZone.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light mb-3" data-bs-theme="light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameZone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Games" asp-action="Index">Games</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>


   

    <a class="sidebar" asp-area="" asp-controller="Home" asp-action=" Index">GameZone</a>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GameZone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>